#### Load Required Libraries

In [25]:
import pandas as pd
import numpy as np
import re

In [21]:
# Create a DataFrame

df = pd.read_csv('personality_scores.csv', delimiter=";")
df_dep =pd.read_csv('departments.csv', sep=';')

#### Examine the data frame for duplicates (based on ID). Drop any duplicates that exist. Use an assert statement to check that the new data frame is the length of the unique entries of the original data frame.

In [22]:
df

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1551,1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1552,1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1553,1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1554,1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
duplicateRowsDF = df[df.duplicated(subset = "ID")]
 
duplicateRowsDF

Empty DataFrame
Columns: [ID, Section 5 of 6 [I am always prepared.], Section 5 of 6 [I am easily disturbed.], Section 5 of 6 [I am exacting (demanding) in my work.], Section 5 of 6 [I am full of ideas.], Section 5 of 6 [I am interested in people.], Section 5 of 6 [I am not interested in abstract ideas.], Section 5 of 6 [I am not interested in other people's problems.], Section 5 of 6 [I am not really interested in others.], Section 5 of 6 [I am quick to understand things.], Section 5 of 6 [I am quiet around strangers.], Section 5 of 6 [I am relaxed most of the time.], Section 5 of 6 [I am the life of the party.], Section 5 of 6 [I change my mood a lot.], Section 5 of 6 [I do not have a good imagination.], Section 5 of 6 [I don't like to draw attention to myself.], Section 5 of 6 [I don't mind being the center of attention.], Section 5 of 6 [I don't talk a lot.], Section 5 of 6 [I feel comfortable around people.], Section 5 of 6 [I feel little concern for others.], Section 5 of 6 [I feel others' emotions.], Section 5 of 6 [I follow a schedule.], Section 5 of 6 [I get chores done right away.], Section 5 of 6 [I get irritated easily.], Section 5 of 6 [I get stressed out easily.], Section 5 of 6 [I get upset easily.], Section 5 of 6 [I have a rich vocabulary.], Section 5 of 6 [I have a soft (kind) heart.], Section 5 of 6 [I have a vivid imagination.], Section 5 of 6 [I have difficulty understanding abstract ideas.], Section 5 of 6 [I have excellent ideas.], Section 5 of 6 [I have frequent mood swings.], Section 5 of 6 [I have little to say.], Section 5 of 6 [I insult people.], Section 5 of 6 [I keep in the background.], Section 5 of 6 [I leave my belongings lying around.], Section 5 of 6 [I like order.], Section 5 of 6 [I make a mess of things.], Section 5 of 6 [I make people feel at ease.], Section 5 of 6 [I neglect my duties.], Section 5 of 6 [I often feel blue (down).], Section 5 of 6 [I often forget to put things back in their proper place], Section 5 of 6 [I pay attention to details.], Section 5 of 6 [I seldom feel blue (down).], Section 5 of 6 [I spend time reflecting on things.], Section 5 of 6 [I start conversations.], Section 5 of 6 [I sympathize with others' feelings.], Section 5 of 6 [I take time out for others.], Section 5 of 6 [I talk to a lot of different people at parties.], Section 5 of 6 [I use difficult words.], Section 5 of 6 [I worry about things.], Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, IPIP_HIGH_RISK]
Index: []

[0 rows x 70 columns]

In [33]:
df_person = df.drop_duplicates(subset='ID')

In [34]:

assert len(df) == len(df_person)

In [54]:
factor = dict({
    1 : 'extraversion', 
    2 : 'agreeableness',
    3 : 'conscientiousness', 
    4 : 'emotional stability',
    5 : 'intellect'})
'''
The function
takes in entry and trait as parameters
(the two values)
'''
def score(entry, trait):

    '''Find  the string of 2 values in an entry and regarding
    them as 2 columns. The score function does this by
    finding the digits in the string 
    and splitting them then regard them
    as columns._r finds the digits in the
    entry of this subcolumn'''
 
    numbers=0
    _r= re.compile('\d+')
    for col in entry:
        num= _r.findall(col)
        if str(trait)==num[0]:
            numbers+= int(num[1])
        else:
            numbers= numbers
    return numbers
factor= dict({
    1 : 'extraversion', 
    2 : 'agreeableness',
    3 : 'conscientiousness', 
    4 : 'emotional stability',
    5 : 'intellect'})
    
for i in factor.keys():
    df_person[f'{factor[i]}']= df_person.loc[:,'Section 5 of 6 [I am always prepared.]':'Section 5 of 6 [I worry about things.]'].apply(score, args=(i,) , axis=1)

In [55]:
df_person

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK,extraversion,agreeableness,conscientiousness,emotional stability,intellect
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,30,40,48,36,42
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,42,46,46,40,42
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,28,40,40,38,42
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,30,38,38,40,38
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,28,34,46,38,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,32,48,38,44,44
1551,1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,40,48,40,44,34
1552,1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,42,44,40,46,48
1553,1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,36,38,48,36,44
1554,1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,22,44,42,40,30

In [39]:
df_dep = pd.read_csv('departments.csv', sep=';')

In [40]:
df_dep

        ID Department
0        0       Data
1        1       Data
2        2       Data
3        3       Data
4        4       Data
...    ...        ...
1550  1550    Web dev
1551  1551    Web dev
1552  1552    Web dev
1553  1553    Web dev
1554  1554    Web dev

[1555 rows x 2 columns]

In [41]:
df_merged = pd.merge(df_person, df_dep, on = 'ID')

In [42]:
df_merged

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK,extraversion,agreeableness,conscientiousness,emotional stability,intellect,Department
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,30,40,48,36,42,Data
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,42,46,46,40,42,Data
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,28,40,40,38,42,Data
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,30,38,38,40,38,Data
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,28,34,46,38,36,Data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,32,48,38,44,44,Web dev
1551,1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,40,48,40,44,34,Web dev
1552,1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,42,44,40,46,48,Web dev
1553,1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,36,38,48,36,44,Web dev
1554,1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,NaN,NaN,NaN,NaN,22,44,42,40,30,Web dev

In [44]:
#Rows
assert len(df_dep) == len(df_merged)

In [48]:
from pandas.util.testing import assert_frame_equal
assert_frame_equal(df_merged,df_merged)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1555 entries, 0 to 1554
Data columns (total 76 columns):
ID                                                                          1555 non-null int64
Section 5 of 6 [I am always prepared.]                                      1555 non-null object
Section 5 of 6 [I am easily disturbed.]                                     1555 non-null object
Section 5 of 6 [I am exacting (demanding) in my work.]                      1555 non-null object
Section 5 of 6 [I am full of ideas.]                                        1555 non-null object
Section 5 of 6 [I am interested in people.]                                 1555 non-null object
Section 5 of 6 [I am not interested in abstract ideas.]                     1555 non-null object
Section 5 of 6 [I am not interested in other people's problems.]            1555 non-null object
Section 5 of 6 [I am not really interested in others.]                      1555 non-null object
Section 5 of 6 [I am quick to understand things.]                           1555 non-null object
Section 5 of 6 [I am quiet around strangers.]                               1555 non-null object
Section 5 of 6 [I am relaxed most of the time.]                             1555 non-null object
Section 5 of 6 [I am the life of the party.]                                1555 non-null object
Section 5 of 6 [I change my mood a lot.]                                    1555 non-null object
Section 5 of 6 [I do not have a good imagination.]                          1555 non-null object
Section 5 of 6 [I don't like to draw attention to myself.]                  1555 non-null object
Section 5 of 6 [I don't mind being the center of attention.]                1555 non-null object
Section 5 of 6 [I don't talk a lot.]                                        1555 non-null object
Section 5 of 6 [I feel comfortable around people.]                          1555 non-null object
Section 5 of 6 [I feel little concern for others.]                          1555 non-null object
Section 5 of 6 [I feel others' emotions.]                                   1555 non-null object
Section 5 of 6 [I follow a schedule.]                                       1555 non-null object
Section 5 of 6 [I get chores done right away.]                              1555 non-null object
Section 5 of 6 [I get irritated easily.]                                    1555 non-null object
Section 5 of 6 [I get stressed out easily.]                                 1555 non-null object
Section 5 of 6 [I get upset easily.]                                        1555 non-null object
Section 5 of 6 [I have a rich vocabulary.]                                  1555 non-null object
Section 5 of 6 [I have a soft (kind) heart.]                                1555 non-null object
Section 5 of 6 [I have a vivid imagination.]                                1555 non-null object
Section 5 of 6 [I have difficulty understanding abstract ideas.]            1555 non-null object
Section 5 of 6 [I have excellent ideas.]                                    1555 non-null object
Section 5 of 6 [I have frequent mood swings.]                               1555 non-null object
Section 5 of 6 [I have little to say.]                                      1555 non-null object
Section 5 of 6 [I insult people.]                                           1555 non-null object
Section 5 of 6 [I keep in the background.]                                  1555 non-null object
Section 5 of 6 [I leave my belongings lying around.]                        1555 non-null object
Section 5 of 6 [I like order.]                                              1555 non-null object
Section 5 of 6 [I make a mess of things.]                                   1555 non-null object
Section 5 of 6 [I make people feel at ease.]                                1555 non-null object
Section 5 of 6 [I neglect my duties.]                                       1555 non-null object
Section 5 of 6 [I often feel blue (down).]                                  1555 non-null object
Section 5 of 6 [I often forget to put things back in their proper place]    1555 non-null object
Section 5 of 6 [I pay attention to details.]                                1555 non-null object
Section 5 of 6 [I seldom feel blue (down).]                                 1555 non-null object
Section 5 of 6 [I spend time reflecting on things.]                         1555 non-null object
Section 5 of 6 [I start conversations.]                                     1555 non-null object
Section 5 of 6 [I sympathize with others' feelings.]                        1555 non-null object
Section 5 of 6 [I take time out for others.]                                1555 non-null object
Section 5 of 6 [I talk to a lot of different people at parties.]            1555 non-null object
Section 5 of 6 [I use difficult words.]                                     1555 non-null object
Section 5 of 6 [I worry about things.]                                      1555 non-null object
Unnamed: 51                                                                 0 non-null float64
Unnamed: 52                                                                 0 non-null float64
Unnamed: 53                                                                 0 non-null float64
Unnamed: 54                                                                 0 non-null float64
Unnamed: 55                                                                 0 non-null float64
Unnamed: 56                                                                 0 non-null float64
Unnamed: 57                                                                 0 non-null float64
Unnamed: 58                                                                 0 non-null float64
Unnamed: 59                                                                 0 non-null float64
Unnamed: 60                                                                 0 non-null float64
Unnamed: 61                                                                 0 non-null float64
Unnamed: 62                                                                 0 non-null float64
Unnamed: 63                                                                 0 non-null float64
Unnamed: 64                                                                 0 non-null float64
Unnamed: 65                                                                 0 non-null float64
Unnamed: 66                                                                 0 non-null float64
Unnamed: 67                                                                 0 non-null float64
Unnamed: 68                                                                 0 non-null float64
IPIP_HIGH_RISK                                                              0 non-null float64
extraversion                                                                1555 non-null int64
agreeableness                                                               1555 non-null int64
conscientiousness                                                           1555 non-null int64
emotional stability                                                         1555 non-null int64
intellect                                                                   1555 non-null int64
Department                                                                  1555 non-null object
dtypes: float64(19), int64(6), object(51)
memory usage: 935.4+ KB